### ISSUE TITLE
Question on the code

### ISSUE THREAD

**Issue by dssrgu** [IBM/Autozoom-Attack#1]
Hi,
I'm trying to understand your code and reproduce the results. While reading through the code, I found that 'o_bestattack' at 'blackbox_attack.py' line 238 first initializes as a non-tanhed image but gets a tanhed image after attack success. Why is it not initialized as a tanhed image? Am I missing something?
Thanks.

**Comment by chunchentu** [comment]
Hi,

The o_bestattack is a variable for storing the best attack results. We initialize it with the original image  and this would not influence the attack. The class attribute USE_TANH will determine if tanh function will be applied on the image or not.

Bests
Chun-Chen
