### ISSUE TITLE
L2dist can‘t convergence

### ISSUE THREAD

**Issue by wzp123456** [IBM/Autozoom-Attack#2]
Hi,
I run your code on my dataset.
After finding the adversarial example, the L2 distance is larger as the number of iterations increases.
It looks like that the estimated gradient can't guide the direction of the drop in L2 distance.
Do you have any advice?
Thanks!

**Comment by chunchentu** [comment]
Hi,

It seems like AutoZOOM cannot find a good estimation for the gradient vector. I would suggest to increase the number of random vector ( specified by the option `num_rand_vec`) to improve the estimation of the gradient vector.

Bests,
Chun-Chen

**Comment by wzp123456** [comment]
Thanks for your reply!
I will try again according to your suggestion.
