### ISSUE TITLE
How to convert the auto-encoder h5 file to pytorch format?

### ISSUE THREAD

**Issue by machanic** [IBM/Autozoom-Attack#7]
I am reproduce the AutoZoom code to pytorch version, but the biggest challenge is the h5 file that is pre-trained by the repo owner. How to train the auto-encoder and which dataset do you use?
Or can I convert the h5 file to the model file that pytorch model can load?

**Comment by chunchentu** [comment]
Hello,

Thank you for being interested in our work.

We only have the tensorflow support for now. You are welcome to contribute the pytorch version.
