### ISSUE TITLE
Bug report, self.real_modifier must be cleared before generate next image.

### ISSUE THREAD

**Issue by machanic** [IBM/Autozoom-Attack#8]
In the original ZOO attack code, before iteratively attack each image(or each mini-batch), the `self.real_modifier.fill(0.0)` is cleared by fill 0. Like this: https://github.com/IBM/ZOO-Attack/blob/master/l2_attack_black.py#L538

Because `self.real_modifier` is an object variable not function scope variable. However, In this repo's code,  you lost this important step, because real_modifier represent the adversarial image's modification and cannot be shared across different images.
I think you should add `self.real_modifier.fill(0.0)` to https://github.com/IBM/Autozoom-Attack/blob/master/blackbox_attack.py#L268

Thanks~

**Comment by chunchentu** [comment]
Thank you for reporting. Add initialization for batch operations.
