### ISSUE TITLE
Bug report, the compress_mode of ImageNet should be 3

### ISSUE THREAD

**Issue by machanic** [IBM/Autozoom-Attack#9]
In https://github.com/IBM/Autozoom-Attack/blob/master/main.py#L303
you set the `args["compress_mode"] = 2`, but in auto encoder , the compress_mode should be 3 according to paper's page 12.

**Comment by chunchentu** [comment]
To correctly load the codec we provided, the compress_mode should be 2. We will update the information shortly.
